version: "3.5"
services:
  apim2_auth:
    container_name: ${APP_NAME}
    hostname: ${APP_NAME}
    networks:
    - LAN
    build:
      context: ./
      dockerfile: Dockerfile
    image: ubuntu16_apache24_php72
    ports:
      - ${APP_PORT}:8080
    volumes:
      - ./:/var/www/html/
    environment:
      DB_HOST: ${DB_HOST}

networks:
  LAN:
    driver: bridge
    name: meng_ting_lan
